export const DUMMY_EMAILS = [
	'Supabase Beta Update - May 2022',
	'Your Apple ID information has been updated.',
	'Save up to $5,000 on a home loan during National Homeownership month',
	"Hello Idaho! We're live in the Gem State",
	'Hulu - More Than Rainbows',
	"Coursera - There's still time to apply for the MSc Applied Data Analytics",
	'SPECIAL OFFIER: Buy 1, Get 1 FREE Tickets to Gimme Gimme Disco',
	"American Express - We've received your payment",
	'Chase - Thank you for scheduling your mortgage payment',
	'[Update] Check your JPMCB - HOME LENDING account',
	'American Express - Your card may not have been present for a purchase',
	'Dominion Energy UT, WY, ID Payment Confirmation',
	'Aspire MasterCard: Do not let this opportunity pass you by!',
	'Question on HR software solutions ($50 opportunity)',
	'Find Public Records For Almost Anyone On This Revolutionary Site!',
	'2 for 1 Concert Tickets! Just in time for summer!',
	'Southwest Airlines - Survey Registration Confirmed',
	'Subject: You have been selected'
];
